modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/fishcute/Celestial/issues"
[[mods]]
modId="celestial"
version="${version}"
displayName="Celestial"
displayURL="https://github.com/fishcute/Celestial"
logoFile="icon.png"
authors="fishcute, block36_"
description='''
A Minecraft mod for Fabric and Forge that allows you to customize the sky.
'''

[[dependencies.celestial]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.celestial]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
